services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'someuser'
      MYSQL_PASSWORD: 'toor'
      MYSQL_ROOT_PASSWORD: 'toor-root'
    volumes:
      - ./data/db:/var/lib/mysql

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api-server
    environment:
      MYSQL_NAME: 'db'
      MYSQL_USER: 'someuser'
      MYSQL_PASSWORD: 'toor'
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:/app

  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp-server
    depends_on:
      - api
  
  # frontend:
  #   build: ./frontend
  #   command: npm start
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true