services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp-server

  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api-server

  frontend:
    build: ./frontend
    command: npm start
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true