# Generated by Django 3.2.18 on 2023-03-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230308_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.customuser')),
                ('channel_name', models.CharField(max_length=40)),
                ('profile_description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='StreamInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.customuser')),
                ('title', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=255)),
                ('stream_description', models.CharField(max_length=1024)),
            ],
        ),
    ]
