# Generated by Django 3.2.18 on 2023-03-09 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_channelinfo_streaminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
